# Run with:
# docker compose -f scripts/docker/compose.openvla-oft.yml up --build

services:
  openvla-oft-deploy:
    build:
      context: ../../openvla-oft
    image: openvla-oft-deploy
    ports:
      - "8777:8777"
    command:
      - --pretrained_checkpoint
      - /models/april_2026_batch2/OpenVLA-OFT-FiLm-3V
      - --unnorm_key
      - aidrc_cups_manipulation_14
      - --host
      - "0.0.0.0"
      - --port
      - "8777"
      - --use_l1_regression
      - "True"
      - --use_diffusion
      - "False"
      - --use_film
      - "True"
      - --num_images_in_input
      - "3"
      - --use_proprio
      - "True"
      - --center_crop
      - "True"
      - --lora_rank
      - "32"
      - --load_in_8bit
      - "False"
      - --load_in_4bit
      - "False"
    volumes:
      - /home/ibrahim/storage/VLA_MODELS:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  openpi_server:
    image: openpi_server
    build:
      context: ../..
      dockerfile: scripts/docker/serve_policy.Dockerfile
    init: true
    tty: true
    network_mode: host
    depends_on:
      openvla-oft-deploy:
        condition: service_started
    volumes:
      - $PWD:/app
      - ${OPENPI_DATA_HOME:-~/.cache/openpi}:/openpi_assets
      - /home/ibrahim/storage/VLA_MODELS:/models
    environment:
      - SERVER_ARGS=--env OPENVLA_OFT
      - OPENPI_DATA_HOME=/openpi_assets
      - IS_DOCKER=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
