# Run with:
# docker compose -f scripts/docker/compose.yml up --build
services:
  openpi_server:
    image: openpi_server
    build:
      context: ../..
      dockerfile: scripts/docker/serve_policy.Dockerfile
    init: true
    tty: true
    network_mode: host
    # Populate configured openpi data home to /openpi_assets inside the container.
    # Populate aws credential inside the container.
    volumes:
      - $PWD:/app
      - ${OPENPI_DATA_HOME:-~/.cache/openpi}:/openpi_assets
      - /home/ibrahim/storage/VLA_MODELS:/models
    environment:
      - SERVER_ARGS=policy:checkpoint --policy.config=FalconVLA-AD14-H10-NP --policy.dir=/models/FalconVLA-8B-ResNet-aidrc_cups_manipulation-org-3v-np-bounds_q99
      - OPENPI_DATA_HOME=/openpi_assets
      - IS_DOCKER=true

    # user: "2200065:2200065"
    # command: bash

    # Comment out this block if not running on a machine with GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
